services:
  # C++ Storage Server (Exercise 2)
  storage-server:
    build:
      context: .
      dockerfile: storage-server/Dockerfile
    container_name: overdrive-storage-server
    environment:
      - OVERDRIVE_PATH=/app/files
    ports:
      - "5555:5555"
    volumes:
      - ./server_data:/app/files
    # Passing Arguments: [Port] [ThreadPoolSize]
    command: ["5555", "10"] 
    networks:
      - overdrive_net
    healthcheck:
      test: ["CMD-SHELL", "pgrep server_main > /dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Node.js Web Server (Exercise 3)
  web-server:
    build:
      context: ./web-server
    container_name: overdrive-web-server
    ports:
      - "3000:3000"
    depends_on:
      storage-server:
        condition: service_healthy
    environment:
      - PORT=3000
      - STORAGE_SERVER_HOST=storage-server
      - STORAGE_SERVER_PORT=5555
      - STORAGE_LIMIT_MB=100
    networks:
      - overdrive_net
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: overdrive-tests
    profiles: ["test"] # Only runs with --profile test
    networks:
      - overdrive_net

  client-cpp:
    build:
      context: .
      dockerfile: Client/Dockerfile.client-cpp
    container_name: overdrive-client-cpp
    depends_on:
      storage-server:
        condition: service_healthy
    profiles: ["client"]
    stdin_open: true
    tty: true
    command: ["storage-server", "5555"]
    networks:
      - overdrive_net

  client-python:
    build:
      context: .
      dockerfile: Client/Dockerfile.client-python
    container_name: overdrive-client-python
    depends_on:
      storage-server:
        condition: service_healthy
    networks:
      - overdrive_net
    stdin_open: true
    tty: true
    command: ["storage-server", "5555"]
    profiles: ["client"]

networks:
  overdrive_net:
    driver: bridge